check 'X-Forecast-API-Call' header is present before reading it
was getting an error:

```
Traceback (most recent call last):
  File "./weather_logging_sparkfun.py", line 227, in <module>
    print(forecast.http_headers['X-Forecast-API-Calls'])
  File "/usr/local/lib/python2.7/dist-packages/requests-2.11.1-py2.7.egg/requests/structures.py", line 54, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'x-forecast-api-calls'
```

in https://darksky.net/dev/docs#response-format it is listed as optional Response Header

From API doc:

    Notes :: Never make any assumptions about the presence of data or lengths of arrays. For example, a lack of data in our data sources may cause data to be missing; or Daylight Savings Time may cause a day to consist of 23 or 25 hours (instead of the usual 24); or, at high latitudes, a given day may not have a sunrise or sunset. Always check for the presence of data before trying to use it.